<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Deterministic>true</Deterministic>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<PublishAot>true</PublishAot>
		<OptimizationPreference>Speed</OptimizationPreference>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<Optimize>true</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
		<DefineConstants>OS_WINDOWS</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(OS)' == 'Unix'">
		<DefineConstants>OS_UNIX</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(OS)' == 'OSX'">
		<DefineConstants>OS_OSX</DefineConstants>
	</PropertyGroup>
</Project>
